### PR TITLE
Sshoc 418 update of springboot version

### PR DESCRIPTION
**Pull request by tparkola**
Closes https://github.com/SSHOC/sshoc-marketplace-backend/issues/418 and https://github.com/SSHOC/sshoc-marketplace-backend/issues/419. Please be aware that these are big changes and there is a need to test the system thoroughly before releasing on production.

### CODE REVIEW

**Comment by KlausIllmayer** [comment]
@tparkola There was an error when building the container, can you have a look?

```
 > [build 6/6] RUN --mount=type=cache,target=/root/.m2 mvn package:
Error: ERROR]   bad class file: /root/.m2/repository/org/springframework/security/spring-security-web/6.2.5/spring-security-web-6.2.5.jar(/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.class)
Error: ERROR]     class file has wrong version 61.0, should be 55.0
Error: ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
Error: ERROR] -> [Help 1]
Error: ERROR] 
Error: ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: ERROR] 
Error: ERROR] For more information about the errors and possible solutions, please read the following articles:
Error: ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
------
```

**Comment by tparkola** [comment]
Hi @KlausIllmayer, not sure on which environment you run this, but the error log indicates that you try to build marketplace with java 11 and not java 17 (minimum requirement for newer spring boot version). So to build app with the upgraded version of spring you need java 17, but I went further and upgraded everything in the marketplace to work with java 21 (the lates LTS version of java). In the Dockerfile java 21 is used (maven:3-eclipse-temurin-21 image to build marketplace and then eclipse-temurin:21 image to run marketplace). Hope that helps.

**Comment by KlausIllmayer** [comment]
thanks for your comment, indeed, that is the issue: for the deployment on the ACDH-CH kubernetes we use the file [Dockerfile-acdh-ch](https://github.com/SSHOC/sshoc-marketplace-backend/blob/develop/Dockerfile-acdh-ch) which was not updated to java 21. If possible, can you please commit changes at Dockerfile also in parallel at Dockerfile-acdh-ch? That would be great, thanks!

**Comment by tparkola** [comment]
Ok, thanks!

**Pull request merged**
